# Generated by Django 5.1.7 on 2025-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a short description of this menu item'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, help_text='Any additional comments or requests (optional)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(help_text="Enter the guest's first name", max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(help_text='Number of guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(help_text="Enter the guest's last name", max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Enter the menu item name', max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(help_text='Enter price in USD or your local currency'),
        ),
    ]
